-- Created once (IF NOT EXISTS), synthetic data generated by Snowflake itself. No files involved.
CREATE TABLE IF NOT EXISTS RAW.CUSTOMERS AS
WITH base AS (
  SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS customer_id,
         UNIFORM(0, 9, RANDOM()) AS f, UNIFORM(0, 7, RANDOM()) AS l,
         UNIFORM(0, 8, RANDOM()) AS c, UNIFORM(0, 600, RANDOM()) AS d
  FROM TABLE(GENERATOR(ROWCOUNT => 1000))
), named AS (
  SELECT customer_id,
         ARRAY_CONSTRUCT('Aarav','Ananya','Rohan','Priya','Kabir','Meera','John','Emma','Liam','Olivia')[f]::STRING AS first_name,
         ARRAY_CONSTRUCT('Sharma','Patel','Singh','Mehta','Iyer','Khan','Smith','Brown')[l]::STRING AS last_name,
         ARRAY_CONSTRUCT('Pune','Mumbai','Delhi','Bengaluru','London','New York','Austin','Toronto','Sydney')[c]::STRING AS city,
         ARRAY_CONSTRUCT('India','India','India','India','UK','USA','USA','Canada','Australia')[c]::STRING AS country,
         DATEADD(day, d, '2024-01-01'::DATE) AS signup_date
  FROM base
)
SELECT customer_id, first_name, last_name,
       LOWER(first_name || '.' || last_name || customer_id || '@example.com') AS email,
       city, country, signup_date
FROM named;

CREATE TABLE IF NOT EXISTS RAW.PRODUCTS AS
WITH base AS (
  SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS product_id, UNIFORM(150, 40000, RANDOM()) AS price
  FROM TABLE(GENERATOR(ROWCOUNT => 40))
)
SELECT product_id,
       ARRAY_CONSTRUCT('Electronics','Home','Books','Fashion','Sports')[MOD(product_id - 1, 5)]::STRING || ' Item ' || product_id AS product_name,
       ARRAY_CONSTRUCT('Electronics','Home','Books','Fashion','Sports')[MOD(product_id - 1, 5)]::STRING AS category,
       (price + 0.99)::NUMBER(12,2) AS unit_price
FROM base;
