-- Run ONCE in a Snowflake worksheet (Projects > Worksheets) as ACCOUNTADMIN.
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS AIRFLOW_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS AIRFLOW_DB;
CREATE SCHEMA IF NOT EXISTS AIRFLOW_DB.RAW;
CREATE SCHEMA IF NOT EXISTS AIRFLOW_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS AIRFLOW_DB.MARTS;

CREATE ROLE IF NOT EXISTS AIRFLOW_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE AIRFLOW_WH TO ROLE AIRFLOW_ROLE;
GRANT ALL ON DATABASE AIRFLOW_DB TO ROLE AIRFLOW_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE AIRFLOW_DB TO ROLE AIRFLOW_ROLE;

-- Dedicated service user for Airflow (better than using your personal login)
CREATE USER IF NOT EXISTS AIRFLOW_USER
  PASSWORD = 'ChangeMe_Str0ng!Pass'   -- change this
  DEFAULT_ROLE = AIRFLOW_ROLE DEFAULT_WAREHOUSE = AIRFLOW_WH
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE AIRFLOW_ROLE TO USER AIRFLOW_USER;

-- Also give the role to your own user so you can query results in the UI
-- GRANT ROLE AIRFLOW_ROLE TO USER <your_login_name>;
