-- OPTIONAL / ADVANCED: let Snowflake read your GitHub repo and run SQL straight from git.
-- Run as ACCOUNTADMIN. If your repo is PUBLIC you can skip the SECRET and GIT_CREDENTIALS lines.
USE ROLE ACCOUNTADMIN;
USE DATABASE AIRFLOW_DB;

CREATE OR REPLACE SECRET AIRFLOW_DB.PUBLIC.GITHUB_SECRET
  TYPE = PASSWORD USERNAME = 'KeshavLakhpati' PASSWORD = '<GITHUB_PERSONAL_ACCESS_TOKEN>';

CREATE OR REPLACE API INTEGRATION GITHUB_API_INT
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/KeshavLakhpati')
  ALLOWED_AUTHENTICATION_SECRETS = (AIRFLOW_DB.PUBLIC.GITHUB_SECRET)
  ENABLED = TRUE;

CREATE OR REPLACE GIT REPOSITORY AIRFLOW_DB.PUBLIC.AIRFLOW_PROJECT_REPO
  API_INTEGRATION = GITHUB_API_INT
  GIT_CREDENTIALS = AIRFLOW_DB.PUBLIC.GITHUB_SECRET
  ORIGIN = 'https://github.com/KeshavLakhpati/airflow-project.git';

ALTER GIT REPOSITORY AIRFLOW_DB.PUBLIC.AIRFLOW_PROJECT_REPO FETCH;
LS @AIRFLOW_DB.PUBLIC.AIRFLOW_PROJECT_REPO/branches/main/;

-- Run a SQL file from git directly:
-- EXECUTE IMMEDIATE FROM @AIRFLOW_DB.PUBLIC.AIRFLOW_PROJECT_REPO/branches/main/include/sql/03_staging.sql;
